### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [pdiezvig/teacozy#3]
https://github.com/pdiezvig/teacozy/blob/master/resources/css/styles.css#L1-L134

Your CSS is short, clean and succinct -- make sure to keep it up! An area of improvement is to make sure to comment your main stylings so that it's clear why you are styling elements in a particular way. Here is a quick reminder on how to comment in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/33445525-11a2c4f2-d5cb-11e7-84a1-94578ba0ab81.png">

**Comment by pdiezvig** [comment]
👍
